import * as React from "react";
import Select from "react-select";

// Comprehensive list of country codes
const COUNTRY_CODES = [
    { value: "+1", label: "+1 (USA/Canada)", country: "US/CA" },
    { value: "+7", label: "+7 (Russia/Kazakhstan)", country: "RU/KZ" },
    { value: "+20", label: "+20 (Egypt)", country: "EG" },
    { value: "+27", label: "+27 (South Africa)", country: "ZA" },
    { value: "+30", label: "+30 (Greece)", country: "GR" },
    { value: "+31", label: "+31 (Netherlands)", country: "NL" },
    { value: "+32", label: "+32 (Belgium)", country: "BE" },
    { value: "+33", label: "+33 (France)", country: "FR" },
    { value: "+34", label: "+34 (Spain)", country: "ES" },
    { value: "+36", label: "+36 (Hungary)", country: "HU" },
    { value: "+39", label: "+39 (Italy)", country: "IT" },
    { value: "+40", label: "+40 (Romania)", country: "RO" },
    { value: "+41", label: "+41 (Switzerland)", country: "CH" },
    { value: "+43", label: "+43 (Austria)", country: "AT" },
    { value: "+44", label: "+44 (UK)", country: "GB" },
    { value: "+45", label: "+45 (Denmark)", country: "DK" },
    { value: "+46", label: "+46 (Sweden)", country: "SE" },
    { value: "+47", label: "+47 (Norway)", country: "NO" },
    { value: "+48", label: "+48 (Poland)", country: "PL" },
    { value: "+49", label: "+49 (Germany)", country: "DE" },
    { value: "+51", label: "+51 (Peru)", country: "PE" },
    { value: "+52", label: "+52 (Mexico)", country: "MX" },
    { value: "+53", label: "+53 (Cuba)", country: "CU" },
    { value: "+54", label: "+54 (Argentina)", country: "AR" },
    { value: "+55", label: "+55 (Brazil)", country: "BR" },
    { value: "+56", label: "+56 (Chile)", country: "CL" },
    { value: "+57", label: "+57 (Colombia)", country: "CO" },
    { value: "+58", label: "+58 (Venezuela)", country: "VE" },
    { value: "+60", label: "+60 (Malaysia)", country: "MY" },
    { value: "+61", label: "+61 (Australia)", country: "AU" },
    { value: "+62", label: "+62 (Indonesia)", country: "ID" },
    { value: "+63", label: "+63 (Philippines)", country: "PH" },
    { value: "+64", label: "+64 (New Zealand)", country: "NZ" },
    { value: "+65", label: "+65 (Singapore)", country: "SG" },
    { value: "+66", label: "+66 (Thailand)", country: "TH" },
    { value: "+81", label: "+81 (Japan)", country: "JP" },
    { value: "+82", label: "+82 (South Korea)", country: "KR" },
    { value: "+84", label: "+84 (Vietnam)", country: "VN" },
    { value: "+86", label: "+86 (China)", country: "CN" },
    { value: "+90", label: "+90 (Turkey)", country: "TR" },
    { value: "+91", label: "+91 (India)", country: "IN" },
    { value: "+92", label: "+92 (Pakistan)", country: "PK" },
    { value: "+93", label: "+93 (Afghanistan)", country: "AF" },
    { value: "+94", label: "+94 (Sri Lanka)", country: "LK" },
    { value: "+95", label: "+95 (Myanmar)", country: "MM" },
    { value: "+98", label: "+98 (Iran)", country: "IR" },
    { value: "+212", label: "+212 (Morocco)", country: "MA" },
    { value: "+213", label: "+213 (Algeria)", country: "DZ" },
    { value: "+216", label: "+216 (Tunisia)", country: "TN" },
    { value: "+218", label: "+218 (Libya)", country: "LY" },
    { value: "+220", label: "+220 (Gambia)", country: "GM" },
    { value: "+221", label: "+221 (Senegal)", country: "SN" },
    { value: "+222", label: "+222 (Mauritania)", country: "MR" },
    { value: "+223", label: "+223 (Mali)", country: "ML" },
    { value: "+224", label: "+224 (Guinea)", country: "GN" },
    { value: "+225", label: "+225 (Ivory Coast)", country: "CI" },
    { value: "+226", label: "+226 (Burkina Faso)", country: "BF" },
    { value: "+227", label: "+227 (Niger)", country: "NE" },
    { value: "+228", label: "+228 (Togo)", country: "TG" },
    { value: "+229", label: "+229 (Benin)", country: "BJ" },
    { value: "+230", label: "+230 (Mauritius)", country: "MU" },
    { value: "+231", label: "+231 (Liberia)", country: "LR" },
    { value: "+232", label: "+232 (Sierra Leone)", country: "SL" },
    { value: "+233", label: "+233 (Ghana)", country: "GH" },
    { value: "+234", label: "+234 (Nigeria)", country: "NG" },
    { value: "+235", label: "+235 (Chad)", country: "TD" },
    { value: "+236", label: "+236 (Central African Republic)", country: "CF" },
    { value: "+237", label: "+237 (Cameroon)", country: "CM" },
    { value: "+238", label: "+238 (Cape Verde)", country: "CV" },
    { value: "+239", label: "+239 (São Tomé and Príncipe)", country: "ST" },
    { value: "+240", label: "+240 (Equatorial Guinea)", country: "GQ" },
    { value: "+241", label: "+241 (Gabon)", country: "GA" },
    { value: "+242", label: "+242 (Republic of the Congo)", country: "CG" },
    { value: "+243", label: "+243 (DR Congo)", country: "CD" },
    { value: "+244", label: "+244 (Angola)", country: "AO" },
    { value: "+245", label: "+245 (Guinea-Bissau)", country: "GW" },
    { value: "+246", label: "+246 (British Indian Ocean Territory)", country: "IO" },
    { value: "+248", label: "+248 (Seychelles)", country: "SC" },
    { value: "+249", label: "+249 (Sudan)", country: "SD" },
    { value: "+250", label: "+250 (Rwanda)", country: "RW" },
    { value: "+251", label: "+251 (Ethiopia)", country: "ET" },
    { value: "+252", label: "+252 (Somalia)", country: "SO" },
    { value: "+253", label: "+253 (Djibouti)", country: "DJ" },
    { value: "+254", label: "+254 (Kenya)", country: "KE" },
    { value: "+255", label: "+255 (Tanzania)", country: "TZ" },
    { value: "+256", label: "+256 (Uganda)", country: "UG" },
    { value: "+257", label: "+257 (Burundi)", country: "BI" },
    { value: "+258", label: "+258 (Mozambique)", country: "MZ" },
    { value: "+260", label: "+260 (Zambia)", country: "ZM" },
    { value: "+261", label: "+261 (Madagascar)", country: "MG" },
    { value: "+262", label: "+262 (Réunion)", country: "RE" },
    { value: "+263", label: "+263 (Zimbabwe)", country: "ZW" },
    { value: "+264", label: "+264 (Namibia)", country: "NA" },
    { value: "+265", label: "+265 (Malawi)", country: "MW" },
    { value: "+266", label: "+266 (Lesotho)", country: "LS" },
    { value: "+267", label: "+267 (Botswana)", country: "BW" },
    { value: "+268", label: "+268 (Eswatini)", country: "SZ" },
    { value: "+269", label: "+269 (Comoros)", country: "KM" },
    { value: "+290", label: "+290 (Saint Helena)", country: "SH" },
    { value: "+291", label: "+291 (Eritrea)", country: "ER" },
    { value: "+297", label: "+297 (Aruba)", country: "AW" },
    { value: "+298", label: "+298 (Faroe Islands)", country: "FO" },
    { value: "+299", label: "+299 (Greenland)", country: "GL" },
    { value: "+350", label: "+350 (Gibraltar)", country: "GI" },
    { value: "+351", label: "+351 (Portugal)", country: "PT" },
    { value: "+352", label: "+352 (Luxembourg)", country: "LU" },
    { value: "+353", label: "+353 (Ireland)", country: "IE" },
    { value: "+354", label: "+354 (Iceland)", country: "IS" },
    { value: "+355", label: "+355 (Albania)", country: "AL" },
    { value: "+356", label: "+356 (Malta)", country: "MT" },
    { value: "+357", label: "+357 (Cyprus)", country: "CY" },
    { value: "+358", label: "+358 (Finland)", country: "FI" },
    { value: "+359", label: "+359 (Bulgaria)", country: "BG" },
    { value: "+370", label: "+370 (Lithuania)", country: "LT" },
    { value: "+371", label: "+371 (Latvia)", country: "LV" },
    { value: "+372", label: "+372 (Estonia)", country: "EE" },
    { value: "+373", label: "+373 (Moldova)", country: "MD" },
    { value: "+374", label: "+374 (Armenia)", country: "AM" },
    { value: "+375", label: "+375 (Belarus)", country: "BY" },
    { value: "+376", label: "+376 (Andorra)", country: "AD" },
    { value: "+377", label: "+377 (Monaco)", country: "MC" },
    { value: "+378", label: "+378 (San Marino)", country: "SM" },
    { value: "+380", label: "+380 (Ukraine)", country: "UA" },
    { value: "+381", label: "+381 (Serbia)", country: "RS" },
    { value: "+382", label: "+382 (Montenegro)", country: "ME" },
    { value: "+383", label: "+383 (Kosovo)", country: "XK" },
    { value: "+385", label: "+385 (Croatia)", country: "HR" },
    { value: "+386", label: "+386 (Slovenia)", country: "SI" },
    { value: "+387", label: "+387 (Bosnia and Herzegovina)", country: "BA" },
    { value: "+389", label: "+389 (North Macedonia)", country: "MK" },
    { value: "+420", label: "+420 (Czech Republic)", country: "CZ" },
    { value: "+421", label: "+421 (Slovakia)", country: "SK" },
    { value: "+423", label: "+423 (Liechtenstein)", country: "LI" },
    { value: "+500", label: "+500 (Falkland Islands)", country: "FK" },
    { value: "+501", label: "+501 (Belize)", country: "BZ" },
    { value: "+502", label: "+502 (Guatemala)", country: "GT" },
    { value: "+503", label: "+503 (El Salvador)", country: "SV" },
    { value: "+504", label: "+504 (Honduras)", country: "HN" },
    { value: "+505", label: "+505 (Nicaragua)", country: "NI" },
    { value: "+506", label: "+506 (Costa Rica)", country: "CR" },
    { value: "+507", label: "+507 (Panama)", country: "PA" },
    { value: "+508", label: "+508 (Saint Pierre and Miquelon)", country: "PM" },
    { value: "+509", label: "+509 (Haiti)", country: "HT" },
    { value: "+590", label: "+590 (Guadeloupe)", country: "GP" },
    { value: "+591", label: "+591 (Bolivia)", country: "BO" },
    { value: "+592", label: "+592 (Guyana)", country: "GY" },
    { value: "+593", label: "+593 (Ecuador)", country: "EC" },
    { value: "+594", label: "+594 (French Guiana)", country: "GF" },
    { value: "+595", label: "+595 (Paraguay)", country: "PY" },
    { value: "+596", label: "+596 (Martinique)", country: "MQ" },
    { value: "+597", label: "+597 (Suriname)", country: "SR" },
    { value: "+598", label: "+598 (Uruguay)", country: "UY" },
    { value: "+599", label: "+599 (Curaçao)", country: "CW" },
    { value: "+670", label: "+670 (Timor-Leste)", country: "TL" },
    { value: "+672", label: "+672 (Antarctica)", country: "AQ" },
    { value: "+673", label: "+673 (Brunei)", country: "BN" },
    { value: "+674", label: "+674 (Nauru)", country: "NR" },
    { value: "+675", label: "+675 (Papua New Guinea)", country: "PG" },
    { value: "+676", label: "+676 (Tonga)", country: "TO" },
    { value: "+677", label: "+677 (Solomon Islands)", country: "SB" },
    { value: "+678", label: "+678 (Vanuatu)", country: "VU" },
    { value: "+679", label: "+679 (Fiji)", country: "FJ" },
    { value: "+680", label: "+680 (Palau)", country: "PW" },
    { value: "+681", label: "+681 (Wallis and Futuna)", country: "WF" },
    { value: "+682", label: "+682 (Cook Islands)", country: "CK" },
    { value: "+683", label: "+683 (Niue)", country: "NU" },
    { value: "+685", label: "+685 (Samoa)", country: "WS" },
    { value: "+686", label: "+686 (Kiribati)", country: "KI" },
    { value: "+687", label: "+687 (New Caledonia)", country: "NC" },
    { value: "+688", label: "+688 (Tuvalu)", country: "TV" },
    { value: "+689", label: "+689 (French Polynesia)", country: "PF" },
    { value: "+690", label: "+690 (Tokelau)", country: "TK" },
    { value: "+691", label: "+691 (Micronesia)", country: "FM" },
    { value: "+692", label: "+692 (Marshall Islands)", country: "MH" },
    { value: "+850", label: "+850 (North Korea)", country: "KP" },
    { value: "+852", label: "+852 (Hong Kong)", country: "HK" },
    { value: "+853", label: "+853 (Macau)", country: "MO" },
    { value: "+855", label: "+855 (Cambodia)", country: "KH" },
    { value: "+856", label: "+856 (Laos)", country: "LA" },
    { value: "+880", label: "+880 (Bangladesh)", country: "BD" },
    { value: "+886", label: "+886 (Taiwan)", country: "TW" },
    { value: "+960", label: "+960 (Maldives)", country: "MV" },
    { value: "+961", label: "+961 (Lebanon)", country: "LB" },
    { value: "+962", label: "+962 (Jordan)", country: "JO" },
    { value: "+963", label: "+963 (Syria)", country: "SY" },
    { value: "+964", label: "+964 (Iraq)", country: "IQ" },
    { value: "+965", label: "+965 (Kuwait)", country: "KW" },
    { value: "+966", label: "+966 (Saudi Arabia)", country: "SA" },
    { value: "+967", label: "+967 (Yemen)", country: "YE" },
    { value: "+968", label: "+968 (Oman)", country: "OM" },
    { value: "+970", label: "+970 (Palestine)", country: "PS" },
    { value: "+971", label: "+971 (UAE)", country: "AE" },
    { value: "+972", label: "+972 (Israel)", country: "IL" },
    { value: "+973", label: "+973 (Bahrain)", country: "BH" },
    { value: "+974", label: "+974 (Qatar)", country: "QA" },
    { value: "+975", label: "+975 (Bhutan)", country: "BT" },
    { value: "+976", label: "+976 (Mongolia)", country: "MN" },
    { value: "+977", label: "+977 (Nepal)", country: "NP" },
    { value: "+992", label: "+992 (Tajikistan)", country: "TJ" },
    { value: "+993", label: "+993 (Turkmenistan)", country: "TM" },
    { value: "+994", label: "+994 (Azerbaijan)", country: "AZ" },
    { value: "+995", label: "+995 (Georgia)", country: "GE" },
    { value: "+996", label: "+996 (Kyrgyzstan)", country: "KG" },
    { value: "+998", label: "+998 (Uzbekistan)", country: "UZ" },
];

const CountrySelect = React.forwardRef(({ value, onChange, className, ...props }, ref) => {
    const selectedOption = COUNTRY_CODES.find(code => code.value === value) || null;

    return (
        <Select
            ref={ref}
            value={selectedOption}
            onChange={(option) => onChange(option?.value || "")}
            options={COUNTRY_CODES}
            className={className}
            classNamePrefix="react-select"
            placeholder="Select code"
            isClearable
            isSearchable
            menuPortalTarget={typeof document !== "undefined" ? document.body : null}
            menuPosition="fixed"
            styles={{
                control: (base) => ({
                    ...base,
                    backgroundColor: "transparent",
                    borderColor: "transparent",
                    minHeight: "100%",
                    borderRadius: "0.65rem",
                    fontSize: "0.875rem",
                    fontWeight: "700",
                    boxShadow: "none",
                    "&:hover": { borderColor: "transparent" },
                }),
                singleValue: (base) => ({ ...base, color: "inherit" }),
                input: (base) => ({ ...base, color: "inherit" }),
                menu: (base) => ({
                    ...base,
                    backgroundColor: "hsl(var(--popover))",
                    borderRadius: "1rem",
                    border: "1px solid hsl(var(--border))",
                    padding: "4px",
                    boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)"
                }),
                menuPortal: (base) => ({ ...base, zIndex: 9999 }),
                option: (base, state) => ({
                    ...base,
                    borderRadius: "0.5rem",
                    margin: "2px 0",
                    backgroundColor: state.isFocused ? "hsl(var(--accent))" : state.isSelected ? "hsl(var(--primary))" : "transparent",
                    color: state.isFocused ? "hsl(var(--accent-foreground))" : state.isSelected ? "hsl(var(--primary-foreground))" : "hsl(var(--foreground))",
                    fontWeight: "600",
                    fontSize: "0.75rem",
                    "&:active": { backgroundColor: "hsl(var(--accent))" }
                }),
                valueContainer: (base) => ({ ...base, padding: "0 12px" }),
            }}
            {...props}
        />
    );
});

CountrySelect.displayName = "CountrySelect";

export { CountrySelect, COUNTRY_CODES };
