-- Migration: Cleanup Phone Directory Duplicates & Reset Legacy Timestamped Entries
-- Date: 2026-08-13
-- Description: Removes bloated legacy duplicate entries generated by non-deterministic timestamped entity IDs (OC_<timestamp>_*)

-- 1. Purge legacy timestamped customer other_contact entries
DELETE FROM phone_directory 
WHERE entity_type = 'other_contact' 
  AND entity_id LIKE 'OC_%' 
  AND entity_id NOT LIKE 'OC_CUST_%';

-- 2. Purge legacy timestamped vendor other_contact entries
DELETE FROM phone_directory 
WHERE entity_type = 'other_contact' 
  AND entity_id LIKE 'OV_%' 
  AND entity_id NOT LIKE 'OV_VEND_%';

-- Note: Running syncDirectory() after applying this migration or triggering directory sync 
-- from the UI/API will completely rebuild a clean, deduplicated directory.
