export const PERMISSIONS = Object.freeze({
    DASHBOARD_VIEW: 'dashboard.view',
    CUSTOMERS_VIEW: 'customers.view',
    CUSTOMERS_CREATE: 'customers.create',
    CUSTOMERS_UPDATE: 'customers.update',
    CUSTOMERS_DELETE: 'customers.delete',
    DOMAINS_VIEW: 'domains.view',
    DOMAINS_CREATE: 'domains.create',
    DOMAINS_UPDATE: 'domains.update',
    DOMAINS_DELETE: 'domains.delete',
    SERVICES_VIEW: 'services.view',
    SERVICES_CREATE: 'services.create',
    SERVICES_UPDATE: 'services.update',
    SERVICES_DELETE: 'services.delete',
    VENDORS_VIEW: 'vendors.view',
    VENDORS_CREATE: 'vendors.create',
    VENDORS_UPDATE: 'vendors.update',
    VENDORS_DELETE: 'vendors.delete',
    SUBSCRIPTIONS_VIEW: 'subscriptions.view',
    SUBSCRIPTIONS_CREATE: 'subscriptions.create',
    SUBSCRIPTIONS_UPDATE: 'subscriptions.update',
    SUBSCRIPTIONS_DELETE: 'subscriptions.delete',
    SUBSCRIPTIONS_SEND_REMINDER: 'subscriptions.send_reminder',
    TAXES_VIEW: 'taxes.view',
    TAXES_CREATE: 'taxes.create',
    TAXES_UPDATE: 'taxes.update',
    TAXES_DELETE: 'taxes.delete',
    TAXES_CONFIGURE: 'taxes.configure',
    USERS_VIEW: 'users.view',
    USERS_CREATE: 'users.create',
    USERS_UPDATE: 'users.update',
    USERS_DELETE: 'users.delete',
    USERS_ASSIGN_ROLES: 'users.assign_roles',
    ROLES_VIEW: 'roles.view',
    ROLES_CREATE: 'roles.create',
    ROLES_UPDATE: 'roles.update',
    ROLES_DELETE: 'roles.delete',
    ROLES_ASSIGN_PERMISSIONS: 'roles.assign_permissions',
    ACTIVITY_LOGS_VIEW: 'activity_logs.view',
    REPORTS_VIEW: 'reports.view',
    SETTINGS_MANAGE: 'settings.manage',
});

export const PERMISSION_DEFINITIONS = [
    { key: PERMISSIONS.DASHBOARD_VIEW, resource: 'dashboard', action: 'view', description: 'Access dashboard widgets' },
    { key: PERMISSIONS.CUSTOMERS_VIEW, resource: 'customers', action: 'view', description: 'View customers' },
    { key: PERMISSIONS.CUSTOMERS_CREATE, resource: 'customers', action: 'create', description: 'Create customers' },
    { key: PERMISSIONS.CUSTOMERS_UPDATE, resource: 'customers', action: 'update', description: 'Update customers' },
    { key: PERMISSIONS.CUSTOMERS_DELETE, resource: 'customers', action: 'delete', description: 'Delete customers' },
    { key: PERMISSIONS.DOMAINS_VIEW, resource: 'domains', action: 'view', description: 'View domains' },
    { key: PERMISSIONS.DOMAINS_CREATE, resource: 'domains', action: 'create', description: 'Create domains' },
    { key: PERMISSIONS.DOMAINS_UPDATE, resource: 'domains', action: 'update', description: 'Update domains' },
    { key: PERMISSIONS.DOMAINS_DELETE, resource: 'domains', action: 'delete', description: 'Delete domains' },
    { key: PERMISSIONS.SERVICES_VIEW, resource: 'services', action: 'view', description: 'View services' },
    { key: PERMISSIONS.SERVICES_CREATE, resource: 'services', action: 'create', description: 'Create services' },
    { key: PERMISSIONS.SERVICES_UPDATE, resource: 'services', action: 'update', description: 'Update services' },
    { key: PERMISSIONS.SERVICES_DELETE, resource: 'services', action: 'delete', description: 'Delete services' },
    { key: PERMISSIONS.VENDORS_VIEW, resource: 'vendors', action: 'view', description: 'View vendors' },
    { key: PERMISSIONS.VENDORS_CREATE, resource: 'vendors', action: 'create', description: 'Create vendors' },
    { key: PERMISSIONS.VENDORS_UPDATE, resource: 'vendors', action: 'update', description: 'Update vendors' },
    { key: PERMISSIONS.VENDORS_DELETE, resource: 'vendors', action: 'delete', description: 'Delete vendors' },
    { key: PERMISSIONS.SUBSCRIPTIONS_VIEW, resource: 'subscriptions', action: 'view', description: 'View subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_CREATE, resource: 'subscriptions', action: 'create', description: 'Create subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_UPDATE, resource: 'subscriptions', action: 'update', description: 'Update subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_DELETE, resource: 'subscriptions', action: 'delete', description: 'Delete subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER, resource: 'subscriptions', action: 'notify', description: 'Send renewal reminders' },
    { key: PERMISSIONS.TAXES_VIEW, resource: 'taxes', action: 'view', description: 'View taxes' },
    { key: PERMISSIONS.TAXES_CREATE, resource: 'taxes', action: 'create', description: 'Create taxes' },
    { key: PERMISSIONS.TAXES_UPDATE, resource: 'taxes', action: 'update', description: 'Update taxes' },
    { key: PERMISSIONS.TAXES_DELETE, resource: 'taxes', action: 'delete', description: 'Delete taxes' },
    { key: PERMISSIONS.TAXES_CONFIGURE, resource: 'taxes', action: 'configure', description: 'Configure default tax settings' },
    { key: PERMISSIONS.USERS_VIEW, resource: 'users', action: 'view', description: 'View users' },
    { key: PERMISSIONS.USERS_CREATE, resource: 'users', action: 'create', description: 'Create users' },
    { key: PERMISSIONS.USERS_UPDATE, resource: 'users', action: 'update', description: 'Update users' },
    { key: PERMISSIONS.USERS_DELETE, resource: 'users', action: 'delete', description: 'Delete users' },
    { key: PERMISSIONS.USERS_ASSIGN_ROLES, resource: 'users', action: 'assign', description: 'Assign roles to users' },
    { key: PERMISSIONS.ROLES_VIEW, resource: 'roles', action: 'view', description: 'View roles' },
    { key: PERMISSIONS.ROLES_CREATE, resource: 'roles', action: 'create', description: 'Create roles' },
    { key: PERMISSIONS.ROLES_UPDATE, resource: 'roles', action: 'update', description: 'Update roles' },
    { key: PERMISSIONS.ROLES_DELETE, resource: 'roles', action: 'delete', description: 'Delete roles' },
    { key: PERMISSIONS.ROLES_ASSIGN_PERMISSIONS, resource: 'roles', action: 'assign', description: 'Assign permissions to roles' },
    { key: PERMISSIONS.ACTIVITY_LOGS_VIEW, resource: 'activity_logs', action: 'view', description: 'View activity logs' },
    { key: PERMISSIONS.REPORTS_VIEW, resource: 'reports', action: 'view', description: 'View reports' },
    { key: PERMISSIONS.SETTINGS_MANAGE, resource: 'settings', action: 'manage', description: 'Manage global settings' },
];

export const DEFAULT_ROLE_PERMISSIONS = {
    admin: PERMISSION_DEFINITIONS.map(({ key }) => key),
    manager: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,
        PERMISSIONS.DOMAINS_VIEW,
        PERMISSIONS.DOMAINS_CREATE,
        PERMISSIONS.DOMAINS_UPDATE,
        PERMISSIONS.SERVICES_VIEW,
        PERMISSIONS.SERVICES_CREATE,
        PERMISSIONS.SERVICES_UPDATE,
        PERMISSIONS.VENDORS_VIEW,
        PERMISSIONS.VENDORS_CREATE,
        PERMISSIONS.VENDORS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_CREATE,
        PERMISSIONS.SUBSCRIPTIONS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER,
        PERMISSIONS.TAXES_VIEW,
        PERMISSIONS.TAXES_UPDATE,
        PERMISSIONS.TAXES_CONFIGURE,
        PERMISSIONS.REPORTS_VIEW,
        PERMISSIONS.SETTINGS_MANAGE,
    ],
    sales: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_CREATE,
        PERMISSIONS.SUBSCRIPTIONS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER,
        PERMISSIONS.REPORTS_VIEW,
    ],
    support: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.DOMAINS_VIEW,
        PERMISSIONS.SERVICES_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER,
    ],
    viewer: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.DOMAINS_VIEW,
        PERMISSIONS.SERVICES_VIEW,
        PERMISSIONS.VENDORS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.TAXES_VIEW,
        PERMISSIONS.REPORTS_VIEW,
    ],
};

