export const PERMISSIONS = Object.freeze({
    DASHBOARD_VIEW: 'dashboard.view',
    CUSTOMERS_VIEW: 'customers.view',
    CUSTOMERS_CREATE: 'customers.create',
    CUSTOMERS_UPDATE: 'customers.update',
    CUSTOMERS_DELETE: 'customers.delete',
    DOMAINS_VIEW: 'domains.view',
    DOMAINS_CREATE: 'domains.create',
    DOMAINS_UPDATE: 'domains.update',
    DOMAINS_DELETE: 'domains.delete',
    SERVICES_VIEW: 'services.view',
    SERVICES_CREATE: 'services.create',
    SERVICES_UPDATE: 'services.update',
    SERVICES_DELETE: 'services.delete',
    VENDORS_VIEW: 'vendors.view',
    VENDORS_CREATE: 'vendors.create',
    VENDORS_UPDATE: 'vendors.update',
    VENDORS_DELETE: 'vendors.delete',
    SUBSCRIPTIONS_VIEW: 'subscriptions.view',
    SUBSCRIPTIONS_CREATE: 'subscriptions.create',
    SUBSCRIPTIONS_UPDATE: 'subscriptions.update',
    SUBSCRIPTIONS_DELETE: 'subscriptions.delete',
    SUBSCRIPTIONS_SEND_REMINDER: 'subscriptions.send_reminder',
    TAXES_VIEW: 'taxes.view',
    TAXES_CREATE: 'taxes.create',
    TAXES_UPDATE: 'taxes.update',
    TAXES_DELETE: 'taxes.delete',
    TAXES_CONFIGURE: 'taxes.configure',
    USERS_VIEW: 'users.view',
    USERS_CREATE: 'users.create',
    USERS_UPDATE: 'users.update',
    USERS_DELETE: 'users.delete',
    USERS_ASSIGN_ROLES: 'users.assign_roles',
    ROLES_VIEW: 'roles.view',
    ROLES_CREATE: 'roles.create',
    ROLES_UPDATE: 'roles.update',
    ROLES_DELETE: 'roles.delete',
    ROLES_ASSIGN_PERMISSIONS: 'roles.assign_permissions',
    ACTIVITY_LOGS_VIEW: 'activity_logs.view',
    REPORTS_VIEW: 'reports.view',
    SETTINGS_MANAGE: 'settings.manage',
    REMINDER_POLICIES_VIEW: 'reminder_policies.view',
    REMINDER_POLICIES_CREATE: 'reminder_policies.create',
    REMINDER_POLICIES_UPDATE: 'reminder_policies.update',
    REMINDER_POLICIES_DELETE: 'reminder_policies.delete',
    EMAIL_TEMPLATES_VIEW: 'email_templates.view',
    EMAIL_TEMPLATES_CREATE: 'email_templates.create',
    EMAIL_TEMPLATES_UPDATE: 'email_templates.update',
    EMAIL_TEMPLATES_DELETE: 'email_templates.delete',
    NOTIFICATION_LOGS_VIEW: 'notification_logs.view',
    QUICK_TOOLS_VIEW: 'quick_tools.view',
    QUICK_TOOLS_MANAGE: 'quick_tools.manage',
    DCR_VIEW: 'dcr.view',
    DCR_CREATE: 'dcr.create',
    DCR_UPDATE: 'dcr.update',
    DCR_DELETE: 'dcr.delete',
    CONTACTS_VIEW: 'contacts.view',
    CONTACTS_CREATE: 'contacts.create',
    CONTACTS_UPDATE: 'contacts.update',
    CONTACTS_DELETE: 'contacts.delete',
    BIRTHDAYS_VIEW: 'birthdays.view',
    BIRTHDAYS_MANAGE: 'birthdays.manage',
    BIRTHDAYS_SYNC: 'birthdays.sync',
    BACKUPS_VIEW: 'backups.view',
    BACKUPS_CREATE: 'backups.create',
    BACKUPS_UPDATE: 'backups.update',
    BACKUPS_DELETE: 'backups.delete',
    BACKUPS_TRIGGER: 'backups.trigger',
    BACKUPS_RESTORE: 'backups.restore',
    BACKUPS_DOWNLOAD: 'backups.download',
});

export const PERMISSION_DEFINITIONS = [
    { key: PERMISSIONS.DASHBOARD_VIEW, resource: 'dashboard', action: 'view', description: 'Access dashboard widgets' },
    { key: PERMISSIONS.CUSTOMERS_VIEW, resource: 'customers', action: 'view', description: 'View customers' },
    { key: PERMISSIONS.CUSTOMERS_CREATE, resource: 'customers', action: 'create', description: 'Create customers' },
    { key: PERMISSIONS.CUSTOMERS_UPDATE, resource: 'customers', action: 'update', description: 'Update customers' },
    { key: PERMISSIONS.CUSTOMERS_DELETE, resource: 'customers', action: 'delete', description: 'Delete customers' },
    { key: PERMISSIONS.DOMAINS_VIEW, resource: 'domains', action: 'view', description: 'View domains' },
    { key: PERMISSIONS.DOMAINS_CREATE, resource: 'domains', action: 'create', description: 'Create domains' },
    { key: PERMISSIONS.DOMAINS_UPDATE, resource: 'domains', action: 'update', description: 'Update domains' },
    { key: PERMISSIONS.DOMAINS_DELETE, resource: 'domains', action: 'delete', description: 'Delete domains' },
    { key: PERMISSIONS.SERVICES_VIEW, resource: 'services', action: 'view', description: 'View services' },
    { key: PERMISSIONS.SERVICES_CREATE, resource: 'services', action: 'create', description: 'Create services' },
    { key: PERMISSIONS.SERVICES_UPDATE, resource: 'services', action: 'update', description: 'Update services' },
    { key: PERMISSIONS.SERVICES_DELETE, resource: 'services', action: 'delete', description: 'Delete services' },
    { key: PERMISSIONS.VENDORS_VIEW, resource: 'vendors', action: 'view', description: 'View vendors' },
    { key: PERMISSIONS.VENDORS_CREATE, resource: 'vendors', action: 'create', description: 'Create vendors' },
    { key: PERMISSIONS.VENDORS_UPDATE, resource: 'vendors', action: 'update', description: 'Update vendors' },
    { key: PERMISSIONS.VENDORS_DELETE, resource: 'vendors', action: 'delete', description: 'Delete vendors' },
    { key: PERMISSIONS.SUBSCRIPTIONS_VIEW, resource: 'subscriptions', action: 'view', description: 'View subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_CREATE, resource: 'subscriptions', action: 'create', description: 'Create subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_UPDATE, resource: 'subscriptions', action: 'update', description: 'Update subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_DELETE, resource: 'subscriptions', action: 'delete', description: 'Delete subscriptions' },
    { key: PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER, resource: 'subscriptions', action: 'notify', description: 'Send renewal reminders' },
    { key: PERMISSIONS.TAXES_VIEW, resource: 'taxes', action: 'view', description: 'View taxes' },
    { key: PERMISSIONS.TAXES_CREATE, resource: 'taxes', action: 'create', description: 'Create taxes' },
    { key: PERMISSIONS.TAXES_UPDATE, resource: 'taxes', action: 'update', description: 'Update taxes' },
    { key: PERMISSIONS.TAXES_DELETE, resource: 'taxes', action: 'delete', description: 'Delete taxes' },
    { key: PERMISSIONS.TAXES_CONFIGURE, resource: 'taxes', action: 'configure', description: 'Configure default tax settings' },
    { key: PERMISSIONS.USERS_VIEW, resource: 'users', action: 'view', description: 'View users' },
    { key: PERMISSIONS.USERS_CREATE, resource: 'users', action: 'create', description: 'Create users' },
    { key: PERMISSIONS.USERS_UPDATE, resource: 'users', action: 'update', description: 'Update users' },
    { key: PERMISSIONS.USERS_DELETE, resource: 'users', action: 'delete', description: 'Delete users' },
    { key: PERMISSIONS.USERS_ASSIGN_ROLES, resource: 'users', action: 'assign', description: 'Assign roles to users' },
    { key: PERMISSIONS.ROLES_VIEW, resource: 'roles', action: 'view', description: 'View roles' },
    { key: PERMISSIONS.ROLES_CREATE, resource: 'roles', action: 'create', description: 'Create roles' },
    { key: PERMISSIONS.ROLES_UPDATE, resource: 'roles', action: 'update', description: 'Update roles' },
    { key: PERMISSIONS.ROLES_DELETE, resource: 'roles', action: 'delete', description: 'Delete roles' },
    { key: PERMISSIONS.ROLES_ASSIGN_PERMISSIONS, resource: 'roles', action: 'assign', description: 'Assign permissions to roles' },
    { key: PERMISSIONS.ACTIVITY_LOGS_VIEW, resource: 'activity_logs', action: 'view', description: 'View activity logs' },
    { key: PERMISSIONS.REPORTS_VIEW, resource: 'reports', action: 'view', description: 'View reports' },
    { key: PERMISSIONS.SETTINGS_MANAGE, resource: 'settings', action: 'manage', description: 'Manage global settings' },
    { key: PERMISSIONS.REMINDER_POLICIES_VIEW, resource: 'reminder_policies', action: 'view', description: 'View reminder policies' },
    { key: PERMISSIONS.REMINDER_POLICIES_CREATE, resource: 'reminder_policies', action: 'create', description: 'Create reminder policies' },
    { key: PERMISSIONS.REMINDER_POLICIES_UPDATE, resource: 'reminder_policies', action: 'update', description: 'Update reminder policies' },
    { key: PERMISSIONS.REMINDER_POLICIES_DELETE, resource: 'reminder_policies', action: 'delete', description: 'Delete reminder policies' },
    { key: PERMISSIONS.EMAIL_TEMPLATES_VIEW, resource: 'email_templates', action: 'view', description: 'View email templates' },
    { key: PERMISSIONS.EMAIL_TEMPLATES_CREATE, resource: 'email_templates', action: 'create', description: 'Create email templates' },
    { key: PERMISSIONS.EMAIL_TEMPLATES_UPDATE, resource: 'email_templates', action: 'update', description: 'Update email templates' },
    { key: PERMISSIONS.EMAIL_TEMPLATES_DELETE, resource: 'email_templates', action: 'delete', description: 'Delete email templates' },
    { key: PERMISSIONS.NOTIFICATION_LOGS_VIEW, resource: 'notification_logs', action: 'view', description: 'View notification logs' },
    { key: PERMISSIONS.QUICK_TOOLS_VIEW, resource: 'quick_tools', action: 'view', description: 'View and use quick tools widget' },
    { key: PERMISSIONS.QUICK_TOOLS_MANAGE, resource: 'quick_tools', action: 'manage', description: 'Manage quick tools (admin only)' },
    { key: PERMISSIONS.DCR_VIEW, resource: 'dcr', action: 'view', description: 'View DCR entries' },
    { key: PERMISSIONS.DCR_CREATE, resource: 'dcr', action: 'create', description: 'Create DCR entries' },
    { key: PERMISSIONS.DCR_UPDATE, resource: 'dcr', action: 'update', description: 'Update DCR entries' },
    { key: PERMISSIONS.DCR_DELETE, resource: 'dcr', action: 'delete', description: 'Delete DCR entries' },
    { key: PERMISSIONS.CONTACTS_VIEW, resource: 'contacts', action: 'view', description: 'View contacts' },
    { key: PERMISSIONS.CONTACTS_CREATE, resource: 'contacts', action: 'create', description: 'Create contacts' },
    { key: PERMISSIONS.CONTACTS_UPDATE, resource: 'contacts', action: 'update', description: 'Update contacts' },
    { key: PERMISSIONS.CONTACTS_DELETE, resource: 'contacts', action: 'delete', description: 'Delete contacts' },
    { key: PERMISSIONS.BIRTHDAYS_VIEW, resource: 'birthdays', action: 'view', description: 'View birthdays' },
    { key: PERMISSIONS.BIRTHDAYS_MANAGE, resource: 'birthdays', action: 'manage', description: 'Manage birthdays' },
    { key: PERMISSIONS.BIRTHDAYS_SYNC, resource: 'birthdays', action: 'sync', description: 'Sync birthdays from source tables' },
    { key: PERMISSIONS.BACKUPS_VIEW, resource: 'backups', action: 'view', description: 'View backup configurations and history' },
    { key: PERMISSIONS.BACKUPS_CREATE, resource: 'backups', action: 'create', description: 'Create backup configurations' },
    { key: PERMISSIONS.BACKUPS_UPDATE, resource: 'backups', action: 'update', description: 'Update backup configurations' },
    { key: PERMISSIONS.BACKUPS_DELETE, resource: 'backups', action: 'delete', description: 'Delete backup configurations' },
    { key: PERMISSIONS.BACKUPS_TRIGGER, resource: 'backups', action: 'trigger', description: 'Manually trigger backups' },
    { key: PERMISSIONS.BACKUPS_RESTORE, resource: 'backups', action: 'restore', description: 'Restore from backups (CRITICAL - Admin only)' },
    { key: PERMISSIONS.BACKUPS_DOWNLOAD, resource: 'backups', action: 'download', description: 'Download backup files' },
];

export const DEFAULT_ROLE_PERMISSIONS = {
    admin: PERMISSION_DEFINITIONS.map(({ key }) => key),
    manager: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,
        PERMISSIONS.DOMAINS_VIEW,
        PERMISSIONS.DOMAINS_CREATE,
        PERMISSIONS.DOMAINS_UPDATE,
        PERMISSIONS.SERVICES_VIEW,
        PERMISSIONS.SERVICES_CREATE,
        PERMISSIONS.SERVICES_UPDATE,
        PERMISSIONS.VENDORS_VIEW,
        PERMISSIONS.VENDORS_CREATE,
        PERMISSIONS.VENDORS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_CREATE,
        PERMISSIONS.SUBSCRIPTIONS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER,
        PERMISSIONS.TAXES_VIEW,
        PERMISSIONS.TAXES_UPDATE,
        PERMISSIONS.TAXES_CONFIGURE,
        PERMISSIONS.REPORTS_VIEW,
        PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.QUICK_TOOLS_VIEW,
        PERMISSIONS.DCR_VIEW,
        PERMISSIONS.DCR_CREATE,
        PERMISSIONS.DCR_UPDATE,
        PERMISSIONS.CONTACTS_VIEW,
        PERMISSIONS.CONTACTS_CREATE,
        PERMISSIONS.CONTACTS_UPDATE,
    ],
    sales: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_CREATE,
        PERMISSIONS.SUBSCRIPTIONS_UPDATE,
        PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER,
        PERMISSIONS.REPORTS_VIEW,
        PERMISSIONS.QUICK_TOOLS_VIEW,
        PERMISSIONS.DCR_VIEW,
        PERMISSIONS.DCR_CREATE,
        PERMISSIONS.DCR_UPDATE,
        PERMISSIONS.CONTACTS_VIEW,
        PERMISSIONS.CONTACTS_CREATE,
        PERMISSIONS.CONTACTS_UPDATE,
    ],
    support: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.DOMAINS_VIEW,
        PERMISSIONS.SERVICES_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_SEND_REMINDER,
        PERMISSIONS.QUICK_TOOLS_VIEW,
        PERMISSIONS.DCR_VIEW,
        PERMISSIONS.DCR_CREATE,
    ],
    viewer: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.DOMAINS_VIEW,
        PERMISSIONS.SERVICES_VIEW,
        PERMISSIONS.VENDORS_VIEW,
        PERMISSIONS.SUBSCRIPTIONS_VIEW,
        PERMISSIONS.TAXES_VIEW,
        PERMISSIONS.REPORTS_VIEW,
        PERMISSIONS.QUICK_TOOLS_VIEW,
        PERMISSIONS.DCR_VIEW,
    ],
};

